name: Build nlp-api image [Python 3.8]
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone git repo onto this {{ ubuntu-latest}} node
      - uses: actions/checkout@v2
      - name Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build using Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies [pip]
        run: |
          python -m pip install pip --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .

      - name: test with linter [flake8]
        run: flake8 .

      - name: Build and Push Docker NLP-API Image
        run: |
          docker build . -t chipembere13/nlp-api:latest
          docker push chipembere13/nlp-api:latest
